name: Build and Push Docker Image
on: 
 push:
 schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '11 11 1 * *'

jobs:
  docker:
    environment: DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: freekers/docker-cod4x17a:latest,freekers/docker-cod4x17a:${{ github.run_number }}
